### ISSUE TITLE
Cannot get property 'imports' on null object

### ISSUE THREAD

**Issue by realdadfish** [reaster/schema-gen#13]
I'm trying to generate Kotlin classes for my XSDs. This is the calling code:

```groovy
class CodeGen extends KotlinGen {
    CodeGen(File schemaFile, File targetDir, String targetPackage) {
        super()
        schemaURL = schemaFile.toURI().toURL()
        srcDir = targetDir
        packageName = targetPackage
        addSuffixToEnumClass = null
        anyPropertyName = 'text'
    }
}
```

The XSD file is valid (and was used to create Java Beans via xjc before), the targetDir is valid as well and exists, the package name is non-empty. When I execute this code in my custom task, I receive the following crash:

```
java.lang.NullPointerException: Cannot get property 'imports' on null object
        at com.javagen.schema.model.MSource$Imports.leftShift(MSource.groovy:83)
        at com.javagen.schema.model.MSource$Imports$leftShift.call(Unknown Source)
        at com.javagen.schema.kotlin.KotlinJacksonCallback$_gen_closure1.doCall(KotlinJacksonCallback.groovy:116)              at com.javagen.schema.kotlin.KotlinJacksonCallback.gen(KotlinJacksonCallback.groovy:113)
        at com.javagen.schema.kotlin.KotlinJacksonCallback$gen.call(Unknown Source)
        at com.javagen.schema.java.JavaGen.visit(JavaGen.groovy:357)
        at com.javagen.schema.xml.XmlSchemaVisitor$visit$2.call(Unknown Source)
        at com.javagen.schema.xml.XmlSchemaVisitor$Trait$Helper.visit(XmlSchemaVisitor.groovy:37)
        at com.javagen.schema.xml.XmlSchemaVisitor$Trait$Helper$visit$1.call(Unknown Source)
        at com.javagen.schema.java.JavaGen.visit(JavaGen.groovy:143)
        at com.javagen.schema.java.JavaGen$visit.callCurrent(Unknown Source)
        at com.javagen.schema.kotlin.KotlinGen.gen(KotlinGen.groovy:186)
        at com.javagen.schema.kotlin.KotlinGen$gen.call(Unknown Source)
```

My Groovy-foo is not good enough to figure out [whats going on here](https://github.com/reaster/schema-gen/blob/master/src/main/groovy/com/javagen/schema/model/MSource.groovy#L104), so maybe you have an idea?

**Comment by realdadfish** [comment]
If I use `JavaGen` instead of `KotlinGen` as base class, the error is almost identical:

```
java.lang.NullPointerException: Cannot get property 'imports' on null object
        at com.javagen.schema.model.MSource$Imports.leftShift(MSource.groovy:83)
        at com.javagen.schema.model.MSource$Imports$leftShift.call(Unknown Source)
        at com.javagen.schema.java.JavaJacksonCallback$_gen_closure1.doCall(JavaJacksonCallback.groovy:108)
        at com.javagen.schema.java.JavaJacksonCallback.gen(JavaJacksonCallback.groovy:105)
        at com.javagen.schema.java.JavaJacksonCallback$gen.call(Unknown Source)
        at com.javagen.schema.java.JavaGen.visit(JavaGen.groovy:357)
        at com.javagen.schema.xml.XmlSchemaVisitor$visit$2.call(Unknown Source)
        at com.javagen.schema.xml.XmlSchemaVisitor$Trait$Helper.visit(XmlSchemaVisitor.groovy:37)
        at com.javagen.schema.xml.XmlSchemaVisitor$Trait$Helper$visit$1.call(Unknown Source)
        at com.javagen.schema.java.JavaGen.visit(JavaGen.groovy:143)
        at com.javagen.schema.java.JavaGen$visit.callCurrent(Unknown Source)
        at com.javagen.schema.java.JavaGen.gen(JavaGen.groovy:126)
        at com.javagen.schema.java.JavaGen$gen$3.call(Unknown Source)
```

**Comment by realdadfish** [comment]
I debugged to it and figured that it recognizes a Boolean type as enum type and then fails to get it's parent class:

![screenshot](http://pasteall.org/pic/show.php?id=bb9fe73a404ba8303cac0fbf8da13c1b)

This is the XSD snippet it stumbles across:

```xsd
    <xs:simpleType name="boolean">
        <xs:restriction base="xs:string">
            <xs:enumeration value="True" />
            <xs:enumeration value="False" />
        </xs:restriction>
    </xs:simpleType>
```

**Comment by realdadfish** [comment]
I wrote some code to flatten the import statement and include all the imported element definitions in the source file. Still, the code exits for the `Boolean` type just as before. I found another issue while testing a different XSD file, I'll open up a separate ticket for that.
