### ISSUE TITLE
When i upgrade the gradle version to 6, below error is coming

### ISSUE THREAD

**Issue by lazy-always** [reaster/schema-gen#16]
When i upgrade the gradle version to 6, below error is coming. The samples in https://github.com/reaster/schema-gen-examples are also failing with the same error.

at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object '[hash, toString, equals, setter, getter, toStringBuilder, adder]' with class 'java.util.ImmutableCollections$SetN' to class 'java.util.EnumSet' due to: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: java.util.EnumSet(com.javagen.schema.model.MMethod$Stereotype, com.javagen.schema.model.MMethod$Stereotype, com.javagen.schema.model.MMethod$Stereotype, com.javagen.schema.model.MMethod$Stereotype, com.javagen.schema.model.MMethod$Stereotype, com.javagen.schema.model.MMethod$Stereotype, com.javagen.schema.model.MMethod$Stereotype)
        at com.javagen.schema.java.JavaPreEmitter.<init>(JavaPreEmitter.groovy:54)

schemaGen {
    java {
        schemaURL = new URL('file:src/main/resources/atom.xsd')
        packageName = 'com.sap.java'
        addSuffixToEnumClass = null
        anyPropertyName = 'text'
    }
}

when i remove the above code,  it works!!! But we need this configuration. Any help???

**Comment by lazy-always** [comment]
the problem is Java version, when i use Java8, it's working. With the Java11, it throws above error.

**Comment by leadtrip** [comment]
I had this problem too, with Gradle 5.1.1 and a Grails project, had to drop back to java 8
